import 'models/category.dart';
import 'models/profile.dart';
import 'models/service.dart';

class Data {
  static List<Category> categories = [
    Category(
      id: 0,
      title: 'Barbershop',
      imagePath: 'assets/categories/barbershop_icon.png',
    ),
    Category(
      id: 1,
      title: 'Fitness',
      imagePath: 'assets/categories/fitness_icon.png',
    ),
    Category(
      id: 2,
      title: 'Learning',
      imagePath: 'assets/categories/learning_icon.png',
    ),
    Category(
      id: 3,
      title: 'Massage',
      imagePath: 'assets/categories/massage_icon.png',
    ),
    Category(
      id: 4,
      title: 'Medicine',
      imagePath: 'assets/categories/medicine_icon.png',
    ),
    Category(
      id: 5,
      title: 'Spa & Beauty',
      imagePath: 'assets/categories/spa_icon.png',
    ),
    Category(
      id: 6,
      title: 'Yoga',
      imagePath: 'assets/categories/yoga_icon.png',
    ),
    Category(
      id: 7,
      title: 'More',
      imagePath: 'assets/categories/more_icon.png',
    ),
  ];

  static List<Service> services = [
    Service(
      id: 0,
      title: 'Premium Men\'s Haircut',
      providerName: 'The Barber Club',
      specialistName: 'Alex Morgan',
      specialistRole: 'Senior Barber',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Classic haircut with wash and styling',
      description:
      'A classic men\'s haircut with wash, style and finishing. Includes consultation.',
      imagePath: 'assets/services/men_haircut.png',
      rating: 4.8,
      reviewsCount: 230,
      price: 25,
      durationMinutes: 30,
      distance: '0.5 km away',
      address: '123 Main Street, Austin, TX',
      tags: ['Hair Wash', 'Haircut', 'Style', 'Consultation'],
      availableTimes: [
        '08:00 AM',
        '10:00 AM',
        '11:00 AM',
        '01:00 PM',
        '03:00 PM',
        '05:00 PM',
      ],
      category: categories[0],
    ),

    Service(
      id: 1,
      title: 'Deep Tissue Massage',
      providerName: 'Pure Wellness Spa',
      specialistName: 'Emma Wilson',
      specialistRole: 'Massage Therapist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Relaxing deep tissue massage',
      description:
      'A focused massage session designed to relieve muscle tension and improve relaxation.',
      imagePath: 'assets/services/massage.jpg',
      rating: 4.4,
      reviewsCount: 156,
      price: 35,
      durationMinutes: 45,
      distance: '0.8 km away',
      address: '45 Wellness Avenue, Austin, TX',
      tags: ['Massage', 'Relaxation', 'Deep Tissue'],
      availableTimes: [
        '09:00 AM',
        '12:00 PM',
        '02:00 PM',
        '04:00 PM',
        '06:00 PM',
      ],
      category: categories[3],
    ),

    Service(
      id: 2,
      title: 'Deep Clean Yoga',
      providerName: 'Balance Yoga Studio',
      specialistName: 'Sophia Reed',
      specialistRole: 'Yoga Instructor',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Calm yoga session for body balance',
      description:
      'A guided yoga class focused on stretching, breathing and restoring body balance.',
      imagePath: 'assets/services/yoga.png',
      rating: 4.7,
      reviewsCount: 98,
      price: 30,
      durationMinutes: 60,
      distance: '1.2 km away',
      address: '18 Harmony Street, Austin, TX',
      tags: ['Yoga', 'Stretching', 'Breathing'],
      availableTimes: [
        '07:00 AM',
        '08:30 AM',
        '10:00 AM',
        '05:30 PM',
        '07:00 PM',
      ],
      category: categories[6],
    ),

    Service(
      id: 3,
      title: 'Bella Salon',
      providerName: 'Bella Salon',
      specialistName: 'Olivia Carter',
      specialistRole: 'Hair Stylist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Hair styling and salon care',
      description:
      'Professional hair styling service with consultation, care and final styling.',
      imagePath: 'assets/services/haircut.png',
      rating: 4.9,
      reviewsCount: 1200,
      price: 40,
      durationMinutes: 50,
      distance: '0.5 km away',
      address: '27 Beauty Road, Austin, TX',
      tags: ['Haircut', 'Styling', 'Salon'],
      availableTimes: [
        '09:30 AM',
        '11:30 AM',
        '01:30 PM',
        '03:30 PM',
        '05:30 PM',
      ],
      category: categories[0],
    ),

    Service(
      id: 4,
      title: 'Pure Wellness Spa',
      providerName: 'Pure Wellness Spa',
      specialistName: 'Mia Brooks',
      specialistRole: 'Spa Therapist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Spa treatment for relaxation',
      description:
      'A relaxing spa treatment that helps reduce stress and refresh the body.',
      imagePath: 'assets/services/spa.jpg',
      rating: 4.2,
      reviewsCount: 84,
      price: 45,
      durationMinutes: 60,
      distance: '0.8 km away',
      address: '45 Wellness Avenue, Austin, TX',
      tags: ['Spa', 'Relaxation', 'Wellness'],
      availableTimes: [
        '10:00 AM',
        '12:00 PM',
        '02:00 PM',
        '04:00 PM',
        '06:00 PM',
      ],
      category: categories[5],
    ),

    // New services below. Images are temporary placeholders.

    Service(
      id: 5,
      title: 'Personal Fitness Training',
      providerName: 'FitLab Studio',
      specialistName: 'Daniel Harris',
      specialistRole: 'Fitness Coach',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'One-on-one fitness coaching',
      description:
      'Personal training session focused on strength, mobility and healthy exercise habits.',
      imagePath: 'assets/services/yoga.png',
      rating: 4.6,
      reviewsCount: 74,
      price: 50,
      durationMinutes: 60,
      distance: '1.0 km away',
      address: '72 Active Street, Austin, TX',
      tags: ['Fitness', 'Training', 'Strength'],
      availableTimes: [
        '06:30 AM',
        '08:00 AM',
        '12:30 PM',
        '05:00 PM',
        '06:30 PM',
      ],
      category: categories[1],
    ),

    Service(
      id: 6,
      title: 'Math Tutoring Session',
      providerName: 'Smart Learning Hub',
      specialistName: 'Grace Miller',
      specialistRole: 'Private Tutor',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Private tutoring for school math',
      description:
      'A personalized tutoring session to help with math topics, homework and exam preparation.',
      imagePath: 'assets/services/men_haircut.png',
      rating: 4.9,
      reviewsCount: 63,
      price: 28,
      durationMinutes: 60,
      distance: '1.5 km away',
      address: '9 Study Lane, Austin, TX',
      tags: ['Tutoring', 'Math', 'Learning'],
      availableTimes: [
        '10:00 AM',
        '01:00 PM',
        '03:00 PM',
        '04:30 PM',
        '06:00 PM',
      ],
      category: categories[2],
    ),

    Service(
      id: 7,
      title: 'General Health Checkup',
      providerName: 'City Medical Clinic',
      specialistName: 'Dr. Ethan Cooper',
      specialistRole: 'General Practitioner',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Basic medical consultation',
      description:
      'A general health checkup with consultation, basic examination and health recommendations.',
      imagePath: 'assets/services/spa.jpg',
      rating: 4.5,
      reviewsCount: 210,
      price: 60,
      durationMinutes: 30,
      distance: '2.0 km away',
      address: '14 Medical Center Road, Austin, TX',
      tags: ['Checkup', 'Consultation', 'Health'],
      availableTimes: [
        '08:30 AM',
        '09:30 AM',
        '11:00 AM',
        '02:30 PM',
        '04:00 PM',
      ],
      category: categories[4],
    ),

    Service(
      id: 8,
      title: 'Beard Grooming',
      providerName: 'The Barber Club',
      specialistName: 'Alex Morgan',
      specialistRole: 'Senior Barber',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Beard trim and grooming',
      description:
      'A beard grooming service with trimming, shaping and styling for a clean look.',
      imagePath: 'assets/services/men_haircut.png',
      rating: 4.7,
      reviewsCount: 180,
      price: 15,
      durationMinutes: 20,
      distance: '0.5 km away',
      address: '123 Main Street, Austin, TX',
      tags: ['Beard', 'Grooming', 'Trim'],
      availableTimes: [
        '09:00 AM',
        '10:30 AM',
        '12:00 PM',
        '02:00 PM',
        '04:30 PM',
      ],
      category: categories[0],
    ),

    Service(
      id: 9,
      title: 'Hair Coloring',
      providerName: 'Bella Salon',
      specialistName: 'Olivia Carter',
      specialistRole: 'Hair Stylist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Professional hair coloring',
      description:
      'Hair coloring service with consultation, color matching and finishing care.',
      imagePath: 'assets/services/haircut.png',
      rating: 4.6,
      reviewsCount: 95,
      price: 45,
      durationMinutes: 60,
      distance: '0.5 km away',
      address: '27 Beauty Road, Austin, TX',
      tags: ['Hair Color', 'Salon', 'Style'],
      availableTimes: [
        '10:00 AM',
        '12:30 PM',
        '03:00 PM',
        '05:00 PM',
      ],
      category: categories[5],
    ),

    Service(
      id: 10,
      title: 'Other Local Service',
      providerName: 'BooklyPro Partner',
      specialistName: 'Chris Taylor',
      specialistRole: 'Service Specialist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'General local service',
      description:
      'A flexible local service provided by a trusted professional near you.',
      imagePath: 'assets/services/spa.jpg',
      rating: 4.3,
      reviewsCount: 41,
      price: 20,
      durationMinutes: 30,
      distance: '1.7 km away',
      address: '31 Local Market Street, Austin, TX',
      tags: ['Local', 'Service', 'Quick Help'],
      availableTimes: [
        '11:00 AM',
        '01:00 PM',
        '03:00 PM',
        '05:00 PM',
      ],
      category: categories[7],
    ),

    Service(
      id: 11,
      title: 'Wellness Consultation',
      providerName: 'Pure Wellness Spa',
      specialistName: 'Nora Bennett',
      specialistRole: 'Wellness Consultant',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Personal wellness advice',
      description:
      'A wellness consultation focused on lifestyle habits, relaxation routines and personal care.',
      imagePath: 'assets/services/spa.jpg',
      rating: 4.5,
      reviewsCount: 67,
      price: 38,
      durationMinutes: 40,
      distance: '0.9 km away',
      address: '45 Wellness Avenue, Austin, TX',
      tags: ['Wellness', 'Consultation', 'Lifestyle'],
      availableTimes: [
        '09:00 AM',
        '11:00 AM',
        '02:00 PM',
        '04:00 PM',
      ],
      category: categories[5],
    ),

    Service(
      id: 12,
      title: 'Beginner Boxing Class',
      providerName: 'FitLab Studio',
      specialistName: 'Marcus Lee',
      specialistRole: 'Boxing Coach',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Boxing basics and cardio',
      description:
      'A beginner-friendly boxing class that combines technique, movement and cardio training.',
      imagePath: 'assets/services/yoga.png',
      rating: 4.4,
      reviewsCount: 52,
      price: 32,
      durationMinutes: 45,
      distance: '1.0 km away',
      address: '72 Active Street, Austin, TX',
      tags: ['Boxing', 'Cardio', 'Fitness'],
      availableTimes: [
        '07:30 AM',
        '12:00 PM',
        '05:30 PM',
        '07:00 PM',
      ],
      category: categories[1],
    ),

    Service(
      id: 13,
      title: 'English Speaking Practice',
      providerName: 'Smart Learning Hub',
      specialistName: 'Emily Stone',
      specialistRole: 'English Tutor',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Private English speaking lesson',
      description:
      'A practical English speaking session focused on vocabulary, fluency and confidence.',
      imagePath: 'assets/services/men_haircut.png',
      rating: 4.8,
      reviewsCount: 89,
      price: 26,
      durationMinutes: 50,
      distance: '1.5 km away',
      address: '9 Study Lane, Austin, TX',
      tags: ['English', 'Speaking', 'Learning'],
      availableTimes: [
        '09:00 AM',
        '12:00 PM',
        '02:00 PM',
        '06:00 PM',
      ],
      category: categories[2],
    ),

    Service(
      id: 14,
      title: 'Dental Consultation',
      providerName: 'City Medical Clinic',
      specialistName: 'Dr. Laura Evans',
      specialistRole: 'Dentist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Basic dental consultation',
      description:
      'A dental consultation with basic examination, recommendations and treatment planning.',
      imagePath: 'assets/services/spa.jpg',
      rating: 4.6,
      reviewsCount: 134,
      price: 55,
      durationMinutes: 30,
      distance: '2.0 km away',
      address: '14 Medical Center Road, Austin, TX',
      tags: ['Dental', 'Consultation', 'Health'],
      availableTimes: [
        '08:00 AM',
        '10:00 AM',
        '01:30 PM',
        '03:30 PM',
      ],
      category: categories[4],
    ),

    Service(
      id: 15,
      title: 'Relaxation Massage',
      providerName: 'Pure Wellness Spa',
      specialistName: 'Emma Wilson',
      specialistRole: 'Massage Therapist',
      specialistImagePath: 'assets/profile/profile.png',
      shortDescription: 'Gentle full-body relaxation massage',
      description:
      'A gentle massage session designed for stress relief, relaxation and body recovery.',
      imagePath: 'assets/services/massage.jpg',
      rating: 4.7,
      reviewsCount: 118,
      price: 42,
      durationMinutes: 60,
      distance: '0.8 km away',
      address: '45 Wellness Avenue, Austin, TX',
      tags: ['Massage', 'Relaxation', 'Recovery'],
      availableTimes: [
        '10:30 AM',
        '01:00 PM',
        '03:30 PM',
        '06:00 PM',
      ],
      category: categories[3],
    ),
  ];

  static Profile profile = Profile(
    name: 'Alex',
    surname: 'Johnson',
    email: 'alex@gmail.com',
    imagePath: 'assets/profile/profile.png',
  );
}